
services:
  backend:
    image: velog_backend:latest
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: my_velog_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ai_service

  ai_service:
    image: velog_ai:latest
    build:
      context: .
      dockerfile: Dockerfile.lang
    container_name: my_velog_ai_service
    ports:
      - "9000:9000"
    volumes:
      - ./ai_service:/app
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      - PYTHONUNBUFFERED=1